### ISSUE TITLE
Camera　interface white SDK: 22, the user manually shut down Camera permissions

### ISSUE THREAD

**Issue by TrustTheBoy** [yonahforst/react-native-permissions#92]
Camera authority is not open, the camera interface is white, how to solve?
PermissionsAndroid only works at SDK> = 23
Will the SDK <23 how to detect whether the user manually closed by the user?

windows 10
phone: Samsung
Android ：5.0

**Comment by iegik** [comment]
No, PermissionsAndroid works only SDK >= 24 👎 
https://github.com/yonahforst/react-native-permissions/blob/master/android/build.gradle#L19

**Comment by PeterEmanuel** [comment]
But doesn't FB recommend the use of SDK 23?

**Comment by iegik** [comment]
No, https://github.com/facebook/react-native/issues/2756
> Yes, it's 4.1 (API 16). This is the version that introduced Choreographer which we make heavy use of, so supporting anything older would be pretty hard. And yes, we should probably document it.
 👍 4

**Comment by yonahforst** [comment]
@TrustTheBoy - in version 1.0.0 I removed all native android code from this lib (using RN's own PermissionsAndroid to avoid additional linking)

That should solve your version conflict!
